name: Webhook Test

on:
  push:
    branches:
      - webhooks

jobs:
  deploy:
    name: 'Webhook'
    runs-on: ubuntu-latest
    steps:
      # https://stackoverflow.com/a/64649397
      - name: Dynamically set $DATE
        run: echo "DATE=$(date +'%Y-%m-%dT%H:%M:%S.000Z')" >> $GITHUB_ENV

      - name: Send webhook
        env:
          TITLE: ':rocket: Deployment Successful!'
          DESCRIPTION: '**Repo:** ${{ github.repository }}\n\n**Commit Hash:** ${{ github.sha }}'
          URL: 'https://github.com/CMPUT301F22T08/AndroidImpact/commit/${{ github.sha }}'
        # The backslashes around double quotes are annoying but if I use single quotes, discord will say the JSON is invalid for some reason
        run: |
          curl \
            -H "Content-Type: application/json" \
            -d "{ \"embeds\": [{ \"title\": \"$TITLE\", \"description\": \"$DESCRIPTION\", \"timestamp\": \"$DATE\", \"url\": \"$URL\" }]}" \
            "${{ secrets.DISCORD_WEBHOOK }}"
